### ISSUE TITLE
Chnage text in Homepage

### ISSUE THREAD

**Issue by PascalLesage** [icra/ecoinvent#30]
**USE THIS TEXT**
The main purpose of the ecoinvent wastewater treatment tool is to generate datasets representing treatment of wastewater with specific composition using specific type of treatment. For more detailed information on the type of methodology used behind this tool, please see the Methodological Report (see the link below).

This tool has been developed within the SRI project and is accessible for free to everybody.

Depending on the context, datasets are generated for the treatment of the wastewater in wastewater treatment plants (WWTP) and for wastewater that is directly discharged to the environment. For the treated fraction, the tool calculates the life cycle inventory of a WWTP (or a set of WWTP) with and without the input of the wastewater for which the datasets are generated, and bases the wastewater-specific life cycle inventory on the difference between the two simulations.

The steps for using the tool are:
    1) Data entry: Enter information about the wastewater of interest: the nature and location of its source, its contamination levels, etc.
    2) Calculation dashboard: Enter or modify the data on the wastewater treatment plants where the wastewater is being treated. The tool will calculate life cycle inventories for the WWTP operating with and without the input of the wastewater.
    3) Generate datasets: The model outputs are converted into datasets, downloadable in ecoSpold2 format.

** AND NO LONGER THIS TEXT**
The ecoinvent wastewater tool was developed to generate ecoinvent-compliant datasets for wastewater that is discharged to the sewer system. It is useful both for data providers that need to supply datasets on the fate of wastewater from the activity they are submitting data for, and for LCA modellers specifically interested in wastewater treatment.

Depending on the context, datasets are generated for the treatment of the wastewater in wastewater treatment plants (WWTP) and for wastewater that is directly discharged to the environment. For the treated fraction, the tool calculates the life cycle inventory of a WWTP (or a set of WWTP) with and without the input of the wastewater for which the datasets are generated, and bases the wastewater-specific life cycle inventory on the difference between the two simulations.

The steps for using the tool are:
    Data entry: Enter information about the wastewater of interest: the nature and location of its source, its contamination levels, etc.
    Calculation dashboard: Enter or modify the data on the wastewater treatment plants where the wastewater is being treated. The tool will calculate life cycle inventories for the WWTP operating with and without the input of the wastewater.
    Generate datasets: The model outputs are converted into datasets, downloadable in ecoSpold format.

The datasets can then be submitted to ecoinvent for inclusion in the database. To do so, the ecoSpold files should be opened in the ecoEditor, checked, and then submitted directly via the ecoEditor.

**Comment by holalluis** [comment]
ok done
