### ISSUE TITLE
Update text in GEnerating ecoSpold2 files

### ISSUE THREAD

**Issue by PascalLesage** [icra/ecoinvent#31]
**USE THIS TEXT**

The generated datasets are in the ecoSpold2 format (.xml). This type of files can be either opened in the ecoEditor (freeware published by ecoinvent), imported into MS Excel, imported into LCA software tools which support import of ecoSpold2 format, opened using XML editor or processed using different types of programming languages (e.g. Python).   

**AND NO LONGER THIS TEXT**

The ecoSpold file(s) can be downloaded. To submit the datasets to ecoinvent:
    Make sure you have installed the ecoEditor freeware and created an account (Menu → Extras → Account management → Register data provider account)
    Open the ecoSpold2 files in the ecoEditor.
    Manually revise the datasets to make sure the fields are correctly filled out. A list of fields to be especially attentive to is given in the methodological report, section 8.3.
    Use ecoEditor to "validate" the datasets (Menu → File → Validate). This will carry out mass balances and make sure all expected fields are filled out.
    Submit the datasets for an external validation (Menu → File → Submit Datasets for Validation). Routines on the ecoinvent server will ensure that the dataset can indeed "fit" in the database.
    Once successful with the previous steps, the datasets can be submitted for review (Menu → File → Submit Datasets for Review). Editors from the ecoinvent editorial board will then review the datasets to make sure they are ok for submission.

Note that if the wastewater treatment datasets were generated in order to have treatment datasets for some other activity, the wastewater treatment datasets should be submitted at the same time or before the other activity, but not after.

**Comment by holalluis** [comment]
ok done
